---
name: Report a bug.
description: Give notice of wrong behavior to let the development team of OpenMarkov to fix it.
labels: ["Priority - Minor", "Status - Pending review"]
type: bug
body:

  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Tell us what happened and what you were expecting to happen.
      placeholder: |
          Example: When opening the properties for a node "A" and giving it a new name "Disease", the name remains at the original name ("A"), while it was expected to change to the new name. 
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps
      description: Tell us what you did in order to get the bug to happen.
      placeholder: |
          Example: 
          1. Open the properties for a node.
          2. Change the name to a new one.
          3. Click on accept.
          At this point, you'll see the network, but the node hasn't changed its name.
    validations:
      required: true

  - type: textarea
    id: log-or-stacktrace
    attributes:
      label: Log or Stacktrace
      render: shell
      description: | 
          If the bug comes from an unexpected error, a dialog will allow you to copy the stacktrace or log. If you aren't given this option, leave a blank.<br>
          <br>
          The log is more useful to us than the stacktrace, but the log might contain sensitive information if you have used any in your session, so you can paste the stacktrace instead.          
      placeholder: |
          2026-09-19 13:17:52,749 [org.openmarkov.gui.dialog.OMExceptionHandler#uncaughtException:49] ERROR:
          java.lang.RuntimeException: Error
          	at org.openmarkov.full@0.3.0-SNAPSHOT/org.openmarkov.full.BreakPointPlugin.lambda$toMenuItem$0(BreakPointPlugin.java:33)
    validations:
      required: false
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What Operating System are you using?
      multiple: false
      options:
        - Windows
        - Linux
        - macOS
      default: 0
    validations:
      required: true

  - type: dropdown
    id: distribution
    attributes:
      label: Distribution
      description: What OpenMarkov distribution are you using?
      multiple: false
      options:
        - .jar file
        - Portable program (.exe)
        - Insalled program (.msi, .exe, .rpm...)
      default: 0
    validations:
      required: true

  - type: upload
    id: files
    attributes:
      label: Upload files
      description: If possible, add files that help to explain the bug, such as screenshots or network files.
    validations:
      required: false

---
