---
name: Report a bug.
description: Give notice of wrong behavior to let the development team of OpenMarkov to fix it.
labels: ["Priority - Minor", "Status - Pending review"]
type: bug
body:

  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Tell us what happened and what you were expecting to happen.
      placeholder: |
          Example: When opening the properties for a node "A" and giving it a new name "Disease", the name remains at the original name ("A"), while it was expected to change to the new name. 
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps
      description: Tell us what you did in order to get the bug to happen.
      placeholder: |
          Example: 
          1. Open the properties for a node.
          2. Change the name to a new one.
          3. Click on accept.
          At this point, you'll see the network, but the node hasn't changed its name.
    validations:
      required: true

  - type: textarea
    id: log-or-stacktrace
    attributes:
      label: Log or Stacktrace
      description: | 
          If this bug led to an unexpected error where you are given the change to copy a log or stacktrace.
          If not applicable, write "Does not apply.".
          The log is more useful to us than the stacktrace, but the log might contain sensitive information if you have used any in your session, so you can paste the stacktrace instead.
      placeholder: |
          Example: 
          1. Open the properties for a node.
          2. Change the name to a new one.
          3. Click on accept.
          At this point, you'll see the network, but the node hasn't changed its name.
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What Operating System are you using?
      multiple: false
      options:
        - Windows
        - Linux
        - macOS
      default: 0
    validations:
      required: true

  - type: dropdown
    id: distribution
    attributes:
      label: Distribution
      description: What OpenMarkov distribution are you using?
      multiple: false
      options:
        - .jar file
        - Portable program (.exe)
        - Insalled program (.msi, .exe, .rpm...)
      default: 0
    validations:
      required: true

  - type: upload
    id: files
    attributes:
      label: Upload files
      description: If possible, add files that help to explain the bug, such as screenshots or network files.
    validations:
      required: false




  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
      
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
          
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

---
